# playbook for ansible, vagrant, and virtualbox hosts
---
- hosts: centos_group,centos8_group,fedora_group,fedora_py3_group,debian_group,ubuntu_group,ubuntu_py3_group
  become: true
  roles:
    - ansible
    - vagrant
    - virtualbox
