---
# defaults file for common module

common_packages:
  - git
  - lsof
  - make
  - net-tools
  - vim
  - wget

# NOTE: group_vars for CentOS8 and Ubuntu 20.04
# redefine common_packages to exclude moreutils 5/16/20
# remove moreutils Ubuntu 20.04 1/7/21

time_host: 0.north-america.pool.ntp.org
time_service: ntpd
timezone: America/Los_Angeles

# https://ubuntuhandbook.org/index.php/2024/04/install-ssh-ubuntu-2404/
# Ubuntu 24.04 uses ssh.socket instead of sshd
# moved sshd restart to Ubuntu_services 6/18/24
sshd_service: sshd

Amazon_packages:
  - amazon-cloudwatch-agent
  - libselinux-python

# CentOS time_service is defined in group_vars/{centos,centos8}_group
# https://bugzilla.redhat.com/show_bug.cgi?id=1820925
# moreutils requires EPEL plus Powertools on CentOS 8
# https://fedoraproject.org/wiki/EPEL#How_can_I_use_these_extra_packages.3F
CentOS_packages:
  - epel-release
  - iproute

# 3/13/22 debian site says to use sntp instead of ntp which is depricated
# running vagrant box from debian only has chrony available
Debian_packages:
  - apt-transport-https

# for some reason moreutils on Fedora32 is on bad repos
# if you install packages manually, many mirrors show code 404 for packages
# regardless of the network connection, trying to add it just times-out.
# https://superuser.com/questions/1035780/how-can-i-use-a-specific-mirror-server-in-fedora 
Fedora_packages:
  - iproute
  - vim-common
  - moreutils

RedHat_packages:
  - iproute
  - moreutils

# Ubuntu time_service is defined in group_vars/{ubuntu,ubuntu_py3}_group
Ubuntu_packages:
  - iproute
  - apt-transport-https
