# install vagrant on Amazon systems
---

- name: selinux required on Amazon
  package:
    name: libselinux-python
    state: present

# installs into /opt/vagrant and /usr/bin/vagrant
- name: installing Amazon rpm file (this may take a minute)
  yum:
    name: "{{ vagrant_url }}/{{ vagrant_rpm_file }}"
    state: present
    disable_gpg_check: yes
  register: vagrant_yum_rpm
# - debug: var=vagrant_yum_rpm.results
