# install vagrant on CentOS systems
---

- name: selinux required on CentOS 7
  package: 
    name: libselinux-python 
    state: present
  when: ansible_distribution_major_version|int < 8

# installs into /opt/vagrant and /usr/bin/vagrant
- name: installing CentOS 7 rpm file (this may take a minute)
  yum:
    name: "{{ vagrant_url }}/{{ vagrant_rpm_file }}"
    state: present
    disable_gpg_check: yes
  register: vagrant_yum_rpm
  when: ansible_distribution_major_version|int == 7
# - debug: var=vagrant_yum_rpm.results

- name: installing CentOS 8 rpm file (this may take a minute)
  dnf:
    name: "{{ vagrant_url }}/{{ vagrant_rpm_file }}"
    state: present
    disable_gpg_check: yes
  register: vagrant_yum_rpm
  when: ansible_distribution_major_version|int > 7
# - debug: var=vagrant_yum_rpm.results
