# install vagrant on Fedora systems
---

- name: python3-libselinux required on Fedora 30+
  package: 
    name: python3-libselinux
    state: present
  when: ansible_distribution_major_version|int > 29

- name: libselinux-python required on Fedora <= 29
  package: 
    name: libselinux-python
    state: present
  when: ansible_distribution_major_version|int <= 29

# vagrant's rpm is signed and requires dnf to install
- name: dnf installing rpm file (this may take a minute)
  dnf:
    name: "{{ vagrant_url }}/{{ vagrant_rpm_file }}"
    state: present
    disable_gpg_check: yes
  register: vagrant_yum_rpm
  when: ansible_distribution_major_version|int >= 22

# - debug: var=vagrant_yum_rpm.results
