# install vagrant on Rocky systems
---

# installs into /opt/vagrant and /usr/bin/vagrant
- name: installing Rocky 8 rpm file (this may take a minute)
  dnf:
    name: "{{ vagrant_url }}/{{ vagrant_rpm_file }}"
    state: present
    disable_gpg_check: yes
  register: vagrant_yum_rpm
# - debug: var=vagrant_yum_rpm.results
