galaxy_info:
  author: "Michael Vilain"
  description: install vagrant
  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 2.8

  platforms:
  - name: Debian
    versions:
    - 10.0 (buster)
    - 11.0 (trusty)
    - 12.0 (bookworm)
  - name: EL
    versions:
    - 6
    - 7
    - 8
  - name: Fedora
    versions:
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
  - name: Ubuntu
    versions:
    - bionic (18.04)
    - focal (20.04)
    - jammy (22.04)

  galaxy_tags:
    - networking

dependencies: []
