---
# handlers file for common

- name: restart ntp time service
  service: 
    name: "{{ time_service }}" 
    state: restarted
  listen: "restart time services"
  register: ts
  when: time_service == "ntp" or time_service == "ntpd"

- name: ntpq peer
  shell: sleep 10 && ntpq -c peer
  register: ntpq_peer
  listen: "restart time services"
  when: time_service == "ntp" or time_service == "ntpd"

#- debug: var=ntpq_peer.stdout_lines
#  listen: "restart time services"
#  when: time_service == "ntpd" or time_service == "ntp"

- name: chrony sources
  shell: sleep 5 && chronyc sources
  register: chronyc
  listen: "restart time services"
  when: time_service == "chronyd" or time_service == "chrony"

- debug: var="{{ item }}"
  with_items:
    - ntpq_peer.stdout_lines
    - chronyc.stdout_lines
  listen: "restart time services"
