# install virtualbox on Amazon systems
---

### this won't work if you're behind a proxy server
- name: adding repo key
  shell: "rpm --import https://www.virtualbox.org/download/oracle_vbox.asc"
  args:
    warn: false
  register: vb_rpm_key
# - debug: var=vb_rpm_key

- name: adding Amazon Linux as RHEL 7 repo
  yum_repository:
    name: virtualbox
    description: Oracle Linux / RHEL / CentOS-7 / $basearch - VirtualBox
    file: virtualbox
    baseurl: http://download.virtualbox.org/virtualbox/rpm/el/7/$basearch
    gpgcheck: yes
    gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    enabled: yes

- name: installing current version (this may take few minutes)
  package:
    name: VirtualBox-6.1
    state: present
  register: vb_install
  when: not is_aws_environment
# - debug: var=vb_install
