# tasks file for virtualbox
---
# get-url uses remote_tmp module internally 2207.22
- name: check for remote_tmp directory used by get-url
  file:
    path: /root/.ansible/tmp
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '1777'
  register: remote_tmp
# - debug: var=remote_tmp

- name: ensure gpg is installed
  package:
    name: gnupg
    state: present

- include_tasks: "{{ ansible_distribution }}-install.yml"
