# install for Ubuntu virtualbox
---
# comparing version with |int will cause a deprecated error in ansible 2.8+
# check to see if release file exists for this version of Ubuntu
- name: verify Virtualbox Release file for this Ubuntu version.
  get_url:
    url: "{{ deb_rel_url }}/dists/{{ ansible_distribution_release }}/Release"
    dest: /tmp/Release
  ignore_errors: yes
  register: ubuntu_release
# - debug: var=ubuntu_release.status_code   # returns "404" if not found

- name: install Virtualbox if Release file exists.
  include_tasks: "{{ ansible_distribution }}-install-valid.yml"
  when: ubuntu_release.status_code|int != 404
