# install for Ubuntu virtualbox
---
# comparing version with |int will cause a deprecated error in ansible 2.8+

# vagrant doesn't support https behind proxy
# none of this won't work behind a proxy server
- name: adding oracle_vbox key
  apt_key:
    url: "{{ deb_vb_keyurl }}/{{ deb_vb_key }}"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version|int >= 18

- name: adding oracle_vbox_2016 key
  apt_key:
    url: "{{ deb_vb_keyurl }}/{{ deb_vb_old_key }}"
    state: present
  when: ansible_distribution_major_version|int == 16 or 
        ansible_distribution_major_version|int == 14


# this may fail for new versions of Virtualbox that don't have their distibutions set up yet.
- name: adding repo
  lineinfile:
    path: /etc/apt/sources.list
    backup: yes
    line: deb https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib
  when: ansible_distribution_major_version|int != 21


# this may fail for new versions of Virtualbox that don't have their distibutions set up yet.
# 11/6/21 VB 6.1.9 doesn't have a Ubuntu 21.10 Release file and so use 21.04's
- name: adding repo
  lineinfile:
    path: /etc/apt/sources.list
    backup: yes
    line: deb https://download.virtualbox.org/virtualbox/debian hirsute contrib
  when: ansible_distribution_major_version|int >= 21

# this may fail for new versions of Virtualbox that don't have their distibutions set up yet.
- name: installing (this may take a few minutes)
  apt:
    name: virtualbox-6.1
    state: present
    allow_unauthenticated: yes
    update_cache: yes
  when: ansible_distribution_major_version|int > 12
  register: vb_install
# - debug: var=vb_install.stdout_lines

- name: installing old release (this may take a few minutes)
  apt:
    name: virtualbox-5.1
    state: latest
    allow_unauthenticated: yes
    update_cache: yes
  when: ansible_distribution_major_version|int == 12
  register: vbold_install
#- debug: var=vbold_install.stdout_lines