# install for Debian ansible
---
# comparing version with |int will cause a deprecated error in ansible 2.8+

# https://tecadmin.net/install-ansible-on-debian-9-stretch/
# apt_repository doesn't work with http sites that don't respond to https requests
# so use brute force approach
# this may fail for new versions of Virtualbox that don't have their distibutions set up yet.
- name: add ansible repository for debian 9
  lineinfile:
    path: /etc/apt/sources.list
    backup: yes
    line: deb http://ppa.launchpad.net/ansible/ansible/ubuntu  trusty main
  when: ansible_distribution_major_version|int == 9

- name: add APT key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367

# needs apt-transport-https package to open http URLs when no https server responds
- name: install on debian
  apt:
    name: ansible
    update_cache: yes
    state: present
