---
# Amazon install tasks for common
# if there are more tasks that split on version,
# put them in their own tasks file. For now two is OK

- name: Amazon packages
  package: name={{ item }} state=present
  with_items:
    - "{{ Amazon_packages }}"

# Amazon uses chrony
- name: Amazon set
  set_fact:
    time_service: chronyd
