# NOTE: THESE CANNOT BE OVERRRIDEN BY THE COMMAND LINE
# os_default vars file for common
# put default values in defaults/main.yml
# host-specific variables can also go here
---
time_service: defaults